config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'homes#top'
  resources :schedules
  resources :groups, only: [:new, :index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :schedules, dependent: :destroy
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User" 
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # スケジュールとのアソシエーション
  has_many :schedules, dependent: :destroy
  # グループ作成のアソシエーション
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  # グループチャットのアソシエーション
  has_many :chats, dependent: :destroy

  # 自分がフォローする
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローしている人を取得
  has_many :followings, through: :relationships, source: :followed
  # 自分がフォローされる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分のフォロワーを取得
  has_many :followers, through: :reverse_of_relationships, source: :follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    schedules_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chats.thml.erb
<div class="chats">
  <p><%= chat.message %></p>
</div>

app/views/groups/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<%= link_to "ログイン", new_user_session_path %> |
<%= link_to "新規登録", new_user_registration_path %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <ul>
    <li><%= link_to "マイカレンダー", schedules_path %></li>
    <li><%= link_to "メンバー一覧", users_index_path %></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourAssistant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/schedules/index.html.erb
<h1>Schedules#index</h1>
<p>Find me in app/views/schedules/index.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users.each do |user| %>
  <%= user.name %>
<% end %>